### ISSUE TITLE
Git push trigger + build

### ISSUE THREAD

**Issue by romuleald** [ricofehr/nextdeploy#2]
It would be lovely to have an option to set on any "develop" VMs an auto-update when the branch is pushed on git

* git pull the VM
* Npm / Grunt / Bower / Gulp
* ComposerInstall

Thanks!

**Comment by ricofehr** [comment]
Ok, this was applied last week. But, actually it was dependent to an agent who check the vm every 30 minutes. So, the "update" of the vm will be not at real time. You can enable thie feature with the new "CI" entry into settings popin (first popin button in the line) associated with your vm.

Fixed with commit d241d8390049ab3b763d8c0f7f878e626dc50260

**Comment by romuleald** [comment]
There's no way to use the [pushEvent](https://developer.github.com/v3/activity/events/types/#pushevent)?

**Comment by ricofehr** [comment]
Maybe on next releases. For now, it's a first and good step on automation of vm update. You can work and push on your work station. And check directly your changes onto your vm just few minutes after. It's already a major  progress and is sufficient in lot of use work.

**Comment by romuleald** [comment]
Ok great, was just asking :)

**Comment by ricofehr** [comment]
Sure, np mr :) I'm taking this point on my side and back to you if there is changes about that.

**Comment by romuleald** [comment]
I'm not able to check the input to allow the auto-update (it's my VM) ![image](https://cloud.githubusercontent.com/assets/144375/16115572/2802b636-33c8-11e6-8027-e5797606577d.png)

**Comment by ricofehr** [comment]
Autant pour moi !
Fixed with commit 7c08143cfe050bf66b9fe334a2f06a5dd3de8ef4
Refresh the webui on your browser for that change takes effect.

**Comment by romuleald** [comment]
you rock! :punch:
